
name: Update README

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Calculate total stars
        id: get_stars
        run: |
          total_stars=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" "https://api.github.com/users/iamfoysal/repos?per_page=100" | jq '[.[] | .stargazers_count] | add')
          echo "::set-output name=stars::$total_stars"

      - name: Update README
        run: |
          stars=${{ steps.get_stars.outputs.stars }}
          sed -i 's/<!--TOTAL_STARS-->/Stars: '"$stars"'/g' README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update total stars in README'
          git push
